config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :tasks
  resources :activities
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :activities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :activities
  has_many :tasks
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
  end

  def new
    @activity = Activity.new
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def show
    @activity = Activity.find(params[:id])
  end

  private
  def task_params
    params[:activity].permit(:duration, :date, :description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def show
    @task = Task.find(params[:id])
  end

  private
  def task_params
    params[:task].permit(:start_date, :end_date, :planned_hours, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @tasks = Task.order("created_at desc")
    @activities = Task.order("created_at desc")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>E-Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <!-- Logo -->
      <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>E-Management</b></span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <!-- Navbar Right Menu -->
      </nav>
    </header>
    <div class="content-wrapper">
      <section class="content">
        <div class="box box-info">
          <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</div>
</section>
</div>
</div>
</body>
</html>

app/views/users/index.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">Recent Task & Activity</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <div class="table-responsive">
      <div class="box">
        <p id="notice"><%= notice %></p>
        <h3 class="box-title">Task Lists</h3>
      </div-->
      <div class="box-body">
        <!--Loop start here-->
        <% @tasks.each do |task| %>
        <div class="attachment-block clearfix">
          <div class="attachment-pushed">
            <h4 class="attachment-heading"></h4>
            <div class="attachment-text" style="margin-top:10px">
              <div class="comment-text" style="margin-top:10px">
                <%= task.planned_hours %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <!--Loop end here-->
      </div>
      <!-- /.box-body -->
      <div class="box-footer"></div>
      <!-- /.box-footer-->
    </div>
  </div>
  <!-- /.table-responsive -->
</div>
  <!-- /.box-body -->
  <!--div class="box-footer clearfix">
    <a href="javascript::;" class="btn btn-sm btn-info btn-flat pull-left">Place New Order</a>
    <a href="javascript::;" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>
  </div-->
  <!-- /.box-footer -->
</div>

<%= link_to 'New Task', new_task_path %> || <%= link_to 'New Activity', new_activity_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>